# Generated by Django 2.1.7 on 2019-03-25 12:59

from django.db import migrations, models


list = (
       {'name':'Ukraine', 'iso_code':'uk', 'status':'active'},
       {'name':'English', 'iso_code':'en', 'status':'disable'},
);

def insert(app, schemaEditor):
    for item in list:
        Language = app.get_model('languages', 'Language')
        language = Language()
        language.name = item['name']
        language.iso_code = item['iso_code']
        language.status = item['status']
        language.main = 'disable'
        language.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('main', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(insert)
    ]