# Generated by Django 2.1.7 on 2019-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='question_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(blank=True, choices=[('question', 'question'), ('answered', 'answered')], default=None, max_length=50),
        ),
    ]
