# Generated by Django 2.1.7 on 2019-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('disable', 'disable')], max_length=50)),
                ('url', models.CharField(blank=True, default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('lang', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
    ]
